automatic_update/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oneApp.urls', namespace='oneApp')),
]

oneApp/urls.py
# -*- coding:utf-8 -*-
"""
# @PROJECT: automatic_update
# @Author: admin
# @Date:   2019-02-13 11:59:18
# @Last Modified by:   admin
# @Last Modified time: 2019-02-13 11:59:18
"""
from django.conf.urls import url
from django.urls import path

from . import views
app_name='oneApp'
urlpatterns = [
    path(r'', views.index, name='index'),   # 首页url
    path(r'england/', views.click_England, name='click_england'),
    path(r'australia/', views.click_Australia, name='click_australia'),
    path(r'canada/', views.click_Canada, name='click_canada'),

    path(r'showResult/<str:country>/<str:up>/', views.show_result, name='show_result'), # 传参数
    path(r'showtable/<str:country>/<int:pageid>/', views.get_monitor_copy1_data, name='get_monitor_copy1_data'),
    path(r'shishixinxi/<str:country>/', views.shishixinxi, name='shishixinxi')
]

oneApp/models.py
from django.db import models

# Create your models here.
class Monitor(models.Model):
    old_id = models.IntegerField(blank=True, null=True)
    sid = models.IntegerField(blank=True, null=True)
    major_name = models.CharField(max_length=255, blank=True, null=True)
    degree_name = models.CharField(max_length=255, blank=True, null=True)
    tuition_fee = models.CharField(max_length=255, blank=True, null=True)
    duration = models.IntegerField(blank=True, null=True)
    state_code = models.IntegerField(blank=True, null=True)
    url_now = models.CharField(max_length=255, blank=True, null=True)
    url_old = models.CharField(max_length=255, blank=True, null=True)
    university = models.CharField(max_length=255, blank=True, null=True)
    update_time = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'monitor'

class Monitor_copy1(models.Model):
    old_id = models.IntegerField(blank=True, null=True)
    sid = models.IntegerField(blank=True, null=True)
    major_name = models.CharField(max_length=255, blank=True, null=True)
    degree_name = models.CharField(max_length=255, blank=True, null=True)
    tuition_fee = models.CharField(max_length=255, blank=True, null=True)
    duration = models.IntegerField(blank=True, null=True)
    state_code = models.IntegerField(blank=True, null=True)
    url_now = models.CharField(max_length=255, blank=True, null=True)
    url_old = models.CharField(max_length=255, blank=True, null=True)
    university = models.CharField(max_length=255, blank=True, null=True)
    update_time = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'monitor_copy1'

oneApp/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.core.paginator import Paginator
import os
from .models import Monitor_copy1


# Create your views here.
# 首页选择需要监控的国家
def index(request):
    # return HttpResponse("Hi 我是首页")
    # if request.session.get('shishixinxi') is None:
    #     request.session['shishixinxi'] = "没有session"
    return render(request, 'oneApp/index.html')


def click_England(request):
    # return HttpResponse("Hi 我是首页111111111111111111111")
    print("===========================", os.getcwd()+r'\jk_en\main.py')
    # if country == "England":
    os.system('python '+os.getcwd()+r'\jk_en\main.py')
    # elif country == "Australia":
    #     os.system('python ' + os.getcwd() + '\jk_au\main.py')
    return redirect(reverse('oneApp:index'))
    # return HttpResponse("Hi 正在监控英国学校。。。。。。。。")

def click_Australia(request):
    print("===========================", os.getcwd()+r'\jk_au\main.py')
    os.system('python ' + os.getcwd() + r'\jk_au\main.py')
    return redirect(reverse('oneApp:index'))

def click_Canada(request):
    print("===========================", os.getcwd()+r'\jk_ca\main.py')
    os.system('python ' + os.getcwd() + r'\jk_ca\main.py')
    return redirect(reverse('oneApp:index'))

# 查看监控结果页面后台逻辑
def show_result(request, country, up):
    # 获取monitor_copy1中的学校数据：404、403、200、200
    # monitor_copy1 = Monitor_copy1.objects.all()
    # print("monitor_copy1: ", monitor_copy1)
    print("country: ", country)

    # 根据开头包含的关键字区分各个国家以及本研
    old_id__startswithU = ''
    old_id__startswithP = ''
    if country == "England":
        old_id__startswithU = 'eu'
        old_id__startswithP = 'ep'
    elif country == "Australia":
        old_id__startswithU = 'au'
        old_id__startswithP = 'ap'
    elif country == "Canada":
        old_id__startswithU = 'cu'
        old_id__startswithP = 'cp'
    elif country == "American":
        old_id__startswithU = 'mu'
        old_id__startswithP = 'mp'
    print("old_id__startswithU: ", old_id__startswithU)
    print("old_id__startswithP: ", old_id__startswithP)

    dataDictU = getData(Monitor_copy1, old_id__startswithU)
    print("dataDictU: ", dataDictU)

    dataDictP = getData(Monitor_copy1, old_id__startswithP)
    print("dataDictP: ", dataDictP)

    contextdict = {}
    contextdict['country'] = country
    contextdict['undergraduate'] = dataDictU
    contextdict['postgraduate'] = dataDictP
    # contextdict = dict(dataDictU, **dataDictP, **{'country': country, "old_id__startswithU": old_id__startswithU, "old_id__startswithP": old_id__startswithP})
    if up == "ug":
        contextdict['up'] = "本科"
    else:
        contextdict['up'] = "研究生"
    print(contextdict)
    return render(request, 'oneApp/show.html', context=contextdict)


# 解析获取各个状态的数据
# 获取monitor_copy1中的学校数据：404、403、200、200
def getData(Monitor_copy1, old_id__startswith):
    dataDict = {}

    # 页面链接失效(404)的数量
    data404 = Monitor_copy1.objects.filter(state_code=404,old_id__startswith=old_id__startswith)
    data404count = data404.count()
    print("data404count==", data404count)
    dataDict['data404number'] = data404count

    # 获取存在404页面的学校名称，存为一个列表
    university404 = []
    if data404.exists():
        for d in data404:
            university404.append(d.university)
            # print(d.university)
    else:
        # 没有数据的情况显示为无
        university404.append("无")
    university404 = list(set(university404))
    dataDict['data404university'] = university404

    # 页面禁止访问(403)的数量
    data403 = Monitor_copy1.objects.filter(state_code=403,old_id__startswith=old_id__startswith)
    data403count = data403.count()
    print("data403count==", data403count)
    dataDict['data403number'] = data403count
    # 获取存在403页面的学校名称，存为一个列表
    university403 = []
    if data403.exists():
        for d in data403:
            university403.append(d.university)
            # print(d.university)
    else:
        university403.append("无")
    university403 = list(set(university403))
    dataDict['data403university'] = university403


    # 页面(200)的数量
    data200 = Monitor_copy1.objects.filter(state_code=200,old_id__startswith=old_id__startswith)
    data200count = data200.count()
    print("data200count==", data200count)

    structure200 = []
    content200 = []
    if data200.exists():
        for d in data200:
            # 判断页面是结构变化，以下四个字段全为空
            if d.major_name is None and d.degree_name is None and d.tuition_fee is None and d.duration is None:
                structure200.append(d.university)
            else:
                content200.append(d.university)
            # content200.append('哈哈哈')

    dataDict['dataStructure200number'] = len(structure200)
    if len(structure200) == 0:
        structure200.append("无")
    dataDict['dataStructure200university'] = list(set(structure200))
    dataDict['dataContent200number'] = len(content200)
    if len(content200) == 0:
        content200.append("无")
    dataDict['dataContent200university'] = list(set(content200))

    return dataDict


# 读取monitor_copy1表数据
def get_monitor_copy1_data(request, country, pageid):
    # 展示字段
    # id、 old_id、 major_name、 degree_name、 tuition_fee、 duration、 state_code、 url_now、 url_old、 university、 update_time、 sid
    # 所有专业数据
    # monitor_copy1 = Monitor_copy1.objects.all()
    print("get_country_key(country).get('old_id__startswithCountry'): ", get_country_key(country))
    monitor_copy1 = Monitor_copy1.objects.filter(old_id__startswith=get_country_key(country).get('old_id__startswithCountry'))
    paginator = Paginator(monitor_copy1, 10)
    page = paginator.page(pageid)
    return render(request, 'oneApp/showtable.html', context={"monitor_copy1": page, 'country': country})
    # return HttpResponse("Hi 正在展示学校数据。。。。。。。。")

# 根据开头包含的关键字区分各个国家
def get_country_key(country):
    old_id__startswithCountry = ''  # 国家
    old_id__startswithU = ''        # 本科
    old_id__startswithP = ''        # 研究生
    if country == "England":
        old_id__startswithCountry = 'e'
        old_id__startswithU = 'eu'
        old_id__startswithP = 'ep'
    elif country == "Australia":
        old_id__startswithCountry = 'a'
        old_id__startswithU = 'au'
        old_id__startswithP = 'ap'
    elif country == "Canada":
        old_id__startswithCountry = 'c'
        old_id__startswithU = 'cu'
        old_id__startswithP = 'cp'
    elif country == "American":
        old_id__startswithCountry = 'm'
        old_id__startswithU = 'mu'
        old_id__startswithP = 'mp'
    return {"old_id__startswithCountry": old_id__startswithCountry, "old_id__startswithU": old_id__startswithU, "old_id__startswithP": old_id__startswithP}


# 获取监控时的实时信息
from django.http import JsonResponse
def shishixinxi(request, country):
    with open(os.getcwd() + "\\"+country+"fileout.txt", 'r', encoding='utf-8') as f:
        last_line = f.readlines()
        # print("last_line: ", last_line)
        # request.session['shishixinxi'] = last_line
    return JsonResponse({"shishixinxi": last_line})

templates/oneApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Histudent数据监控更新系统V1.0</title>
    <style>
         body{
             margin: 0;
             padding: 0;
         }
        #main{
            width: 800px;
            height:500px;
            border: dimgray 3px solid;
            margin: 5px auto;
        }

        ul{
            list-style-type: none;
            margin: auto 50px;
        }

        li{
            float: left;
            width: 120px;
            height: 50px;
            margin: 20px;
            border: dimgray 1px solid;
            background: pink;

        }
        a{
            display: block;
            text-align: center;
            text-decoration: none;
            width: 120px;
            height: 26px;
            padding:12px 0;
            color: black;
            font-size: large;
        }

        a:hover{
            background: skyblue;
            color: red;
        }
        #tost{
            background: rgba(0, 0, 0, .6);
            position: fixed;
            top:0;
            left: 0;
            width: 100%;
            height: 100%;
            display: none;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }
        #txt{
            color: white;
            text-align: center;
            font-size: 30px;
        }
        .button button{
            height: 35px;
            width: 100px;
            border-radius: 10px;
            border: 0;
            margin: 20px;
        }
        .button button a{
            width: 100%;
            height: 100%;
            padding: 0;
            margin: 0;
            line-height: 35px;
        }
        .button button a:hover{
            background: none;

        }
        #shishixinxi{
            margin-left: 100px;
            color: #c2ff07;
            font-size: 38px;
            font-weight: bold;
        }
    </style>
    {% load staticfiles %}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script>
        function showTost(info){
            document.getElementById('tost').style.display = 'flex';
            document.getElementById('txt').innerHTML = '正在监控'+info+'国家院校······';
            console.log(info);
            if(info == "英国")
                tmp = 'England';
            if(info == '澳洲')
                tmp = 'Australia';
            if(info == "加拿大")
                tmp = 'Canada';
            if(info == "美国")
                tmp = 'American';
            console.log(tmp)
            document.getElementById('showresult').href = "/showtable/" +tmp+ "/1";
            console.log("====", document.getElementById('showresult').href);

            setInterval(function () {
                $.ajax({
                    type:"get",
                    {#url:"{% url 'oneApp:shishixinxi' 'England' %}",#}
                    url:"/shishixinxi/"+tmp+"/",
                    dataType:"json",
                    success:function(data, status){
                        console.log("data= ", data[1])
                        var d = data["shishixinxi"]
                        //console.log(d.length)
                        for(var i = 0; i < d.length; i++){
                            document.getElementById("shishixinxi").innerHTML = d[d.length-1]
                        }
                    }
                });
            },500);
            return tmp
        }
        function showCountry() {

        }
        function button1(){
            history.go(0);
            console.log(111)
        }
        function button2(){

        }
    </script>
</head>
<body>
<h1 align="center">Histudent数据监控更新系统V1.0</h1>
<div id="main">
    <h4 style="margin: 30px 40px">点击选择需要监控的国家</h4>
    <ul>
        <li><a href="{% url 'oneApp:click_england' %}" onclick="showTost('英国')">英国</a></li>
        <li><a href="{% url 'oneApp:click_australia' %}" onclick="showTost('澳洲')">澳洲</a></li>
        <li><a href="{% url 'oneApp:click_canada' %}" onclick="showTost('加拿大')">加拿大</a></li>
        <li><a href="#" onclick="showTost('美国')">美国</a></li>
    </ul>
</div>
<div id="tost">
    <div id='txt'>正在监控英国国家院校</div><br>
    <span id="shishixinxi">xiaoaoao</span><br>
    <div class="button">

        <button onclick="button1()"><a href="#">取消</a></button>
        <button><a id="showresult">查看结果</a></button>

    </div>
</div>
</body>

</html>

templates/oneApp/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="vie'wport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/echarts/4.1.0/echarts.min.js"></script>
    <title>统计表</title>
    <style>
        *{
            margin:0;
            padding:0;
            list-style: none;
        }
        table {
            border-collapse:collapse;
            margin: 50px auto;
        }
        table,th, td{
            border: 1px solid #ccc;
        }
        th{
            height:70px;
            background: #eee;
            font-size: 22px;
        }
        td{
            height:60px;
            text-align: center;
            font-size: 18px;
        }
        select, select option{
            height: 60px;
            border: none;
            width: 80%;
            outline: none;
            font-size: 18px;
        }
        #charts{
			height: 500px;
			width: 800px;
			margin: auto;
		}

    </style>
</head>
<body>
<h1 align="center" style="margin: 30px 0 0 0">{{ country }}{{ up }}监控结果</h1>
   <table>
        <tr>
            <th width="200">类型</th>
            <th width="180">数量</th>
            <th width="400">学校</th>
        </tr>
        <tr>
            <td>页面链接失效(404)</td>
            <td id="num1"></td>
            <td>
                <select name="" id="select_id1"></select>
            </td>
        </tr>
        <tr>
            <td>页面禁止访问(403)</td>
            <td id="num2"></td>
            <td>
                <select name="" id="select_id2"></select>
            </td>
        </tr>
        <tr>
            <td>页面结构变化(200)</td>
            <td id="num3"></td>
            <td>
                <select name="" id="select_id3"></select>
            </td>
        </tr>
        <tr>
            <td>页面内容变化(200)</td>
            <td id="num4"></td>
            <td>
                <select name="" id="select_id4"></select>
            </td>
        </tr>
   </table>
<div id="charts">

   </div>

<script>
        console.log("{{ undergraduate }},本科字典====");
        // 判断是本科还是研究生
        {% ifequal up "本科" %}
            //var arr1 = ['学校一','学校2','学校3'];    // 页面链接失效404
            var arr1 = new Array();
            {% for a1 in undergraduate.data404university %}
                {#console.log(a1, "---a1");#}
                arr1.push("{{ a1 }}");
            {% endfor %}
            console.log(arr1, "---arr1");

            //var arr2 = ['学校11','学校22','学校33','学校3sds3'];   // 页面禁止访问403
            var arr2 = new Array();
            {% for a2 in undergraduate.data403university %}
                arr2.push("{{ a2 }}");
            {% endfor %}

            //var arr3 = ['学校111','学校222','学校333','学校44444'];  // 页面结构变化200
            var arr3 = new Array();
            {% for a3 in undergraduate.dataStructure200university %}
                arr3.push("{{ a3 }}");
            {% endfor %}

            //var arr4 = new Array('[{{ dataContent200university }}]');  // 页面内容变化200
            var arr4 = new Array();
            {% for a4 in undergraduate.dataContent200university %}
                arr4.push("{{ a4 }}");
            {% endfor %}
            //console.log(arr4,"==***==");

    {#        var t = tmp + 'data404number';#}
    {#        console.log(t, "**1**", 'audata404number');#}
            var num1 = {{ undergraduate.data404number }};  // 页面链接失效数量
            var num1Con = document.getElementById('num1'); num1Con.innerText = num1;

            {#var t2 = tmp + 'data403number';#}
            var num2 = {{ undergraduate.data403number }};  // 页面禁止访问数量
            var num2Con = document.getElementById('num2'); num2Con.innerText = num2;

            {#var t3 = tmp + 'dataStructure200number';#}
            var num3 = {{ undergraduate.dataStructure200number }};  // 页面结构变化数量
            var num3Con = document.getElementById('num3'); num3Con.innerText = num3;

            {#var t4 = tmp + 'dataContent200number';#}
            var num4 = {{ undergraduate.dataContent200number }};  // 页面内容变化数量
            var num4Con = document.getElementById('num4'); num4Con.innerText = num4;
            var objSelectet1 = document.getElementById('select_id1');
            var objSelectet2 = document.getElementById('select_id2');
            var objSelectet3 = document.getElementById('select_id3');
            var objSelectet4 = document.getElementById('select_id4');

        {% endifequal %}

        {% ifequal up "研究生" %}
            //var arr1 = ['学校一','学校2','学校3'];    // 页面链接失效404
            var arr1 = new Array();
            {% for a1 in postgraduate.data404university %}
                {#console.log(a1, "---a1");#}
                arr1.push("{{ a1 }}");
            {% endfor %}
            console.log(arr1, "---arr1");

            //var arr2 = ['学校11','学校22','学校33','学校3sds3'];   // 页面禁止访问403
            var arr2 = new Array();
            {% for a2 in postgraduate.data403university %}
                arr2.push("{{ a2 }}");
            {% endfor %}

            //var arr3 = ['学校111','学校222','学校333','学校44444'];  // 页面结构变化200
            var arr3 = new Array();
            {% for a3 in postgraduate.dataStructure200university %}
                arr3.push("{{ a3 }}");
            {% endfor %}

            //var arr4 = new Array('[{{ dataContent200university }}]');  // 页面内容变化200
            var arr4 = new Array();
            {% for a4 in postgraduate.dataContent200university %}
                arr4.push("{{ a4 }}");
            {% endfor %}
            //console.log(arr4,"==***==");

            var num1 = {{ postgraduate.data404number }};  // 页面链接失效数量
            var num1Con = document.getElementById('num1'); num1Con.innerText = num1;
            var num2 = {{ postgraduate.data403number }};  // 页面禁止访问数量
            var num2Con = document.getElementById('num2'); num2Con.innerText = num2;
            var num3 = {{ postgraduate.dataStructure200number }};  // 页面结构变化数量
            var num3Con = document.getElementById('num3'); num3Con.innerText = num3;
            var num4 = {{ postgraduate.dataContent200number }};  // 页面内容变化数量
            var num4Con = document.getElementById('num4'); num4Con.innerText = num4;
            var objSelectet1 = document.getElementById('select_id1');
            var objSelectet2 = document.getElementById('select_id2');
            var objSelectet3 = document.getElementById('select_id3');
            var objSelectet4 = document.getElementById('select_id4');

        {% endifequal %}

        // 页面链接失效
        for(var i = 0 ; i < arr1.length ; i++){ 
            var objOption = document.createElement("OPTION");
            objSelectet1.options.add(objOption);
            objOption.text= arr1[i];
        } 
        
        // 页面禁止访问
        for(var i = 0 ; i < arr2.length ; i++){ 
            var objOption = document.createElement("OPTION");
            objSelectet2.options.add(objOption);
            objOption.text= arr2[i];
        } 

        // 页面结构变化
        for(var i = 0 ; i < arr3.length ; i++){ 
            var objOption = document.createElement("OPTION");
            objSelectet3.options.add(objOption);
            objOption.text= arr3[i];
        } 

        // 页面内容变化
        for(var i = 0 ; i < arr4.length ; i++){ 
            var objOption = document.createElement("OPTION");
            objSelectet4.options.add(objOption);
            objOption.text= arr4[i];
        }


        // 饼图
		var myChart = echarts.init(document.getElementById('charts'));

        // 指定图表的配置项和数据
        var option = {
			series: [
				{
					name: '访问来源',
					type: 'pie',
					radius: '55%',
					data:[
						{value:num1, name:'页面链接失效(404)'},
						{value:num2, name:'页面禁止访问(403)'},
						{value:num3, name:'页面结构变化(200)'},
						{value:num4, name:'页面内容变化(200)'},
					]
				}
			]
		};

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

   </script>
</body>
</html>

templates/oneApp/showtable.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="vie'wport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/echarts/4.1.0/echarts.min.js"></script>
    <title>数据展示结果</title>
    <style>
        *{
            margin:0;
            padding:0;
            list-style: none;
        }
        table {
            border-collapse:collapse;
            margin: 50px auto;
        }
        table,th, td{
            border: 1px solid #ccc;
        }
        th{
            height:70px;
            background: #eee;
            font-size: 16px;
        }
        td{
            height:60px;
            text-align: center;
            font-size: 12px;
        }
        select, select option{
            height: 60px;
            border: none;
            width: 80%;
            outline: none;
            font-size: 18px;
        }
        ul{
			{#height: 500px;#}
			{#width: 800px;#}
			margin: auto 200px;
		}
        li{
            width: auto;
            height: 30px;
            text-align: center;
            line-height: 30px;
            float: left;
            {#border: #cccccc 1px solid;#}
            margin-left: 30px;
            color: red;
        }
        li a{
            display: block;
            {#width: 30px;#}
            height: 30px;
            text-decoration: none;
            font-style: oblique;
            color: blue;
        }
        li a:hover{
            background: #dedede;
        }
        .gotoresult{
            font-style: normal;
            color: #dedddb;
        }
        .gotoresult a{
            display: block;
            width: 200px;
            height: 30px;
            background: #dedddb;
            color: red;
        }
        .gotoresult a:hover{
            background: #c7c6c4;
        }
        .statecode{
            width: auto;
            height: 500px;
            text-align: center;
            float: left;
            {#border: #cccccc 1px solid;#}
            margin: 30px auto auto 300px;
        }
        .statecode li{
            color: black;
        }
        .statecode li span{
            font-weight: bold;
            {#font-size: 20px;#}
        }
    </style>
</head>
<body>
<h1 align="center" style="margin: 30px 0 0 0">{{ country }}数据展示</h1>
<table class="layui-table">
    <colgroup>
        <col width="150">
        <col width="150">
        <col width="200">
        <col>
    </colgroup>
    <thead>
    <tr>
        <th>id</th>
        <th>old_id(原数据库id)</th>
        <th>university(学校名)</th>
        <th>major_name(专业名)</th>
        <th>degree_name(学位名称)</th>
        <th>tuition_fee(学费)</th>
        <th>duration(课程长度)</th>
        <th>state code(状态码)</th>
        <th>url now(新链接)</th>
        <th>url old(旧链接)</th>
        <th>update time(更新时间)</th>
    </tr>
    </thead>
    <tbody>
    {% for monitor in monitor_copy1 %}
    <tr>
        <td>{{ monitor.id }}</td>
        <td>{{ monitor.old_id }}</td>
        <td>{{ monitor.university }}</td>
        <td>{{ monitor.major_name }}</td>
        <td>{{ monitor.degree_name }}</td>
        <td>{{ monitor.tuition_fee }}</td>
        <td>{{ monitor.duration }}</td>
        <td>{{ monitor.state_code }}</td>
        <td><a href="{{ monitor.url_now }}" target="_blank">{{ monitor.url_now }}</a></td>
        <td><a href="{{ monitor.url_old }}" target="_blank">{{ monitor.url_old }}</a></td>
        <td>{{ monitor.update_time }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<ul>
    {% if monitor_copy1.has_previous %}
        <li>
        <a href="/showtable/{{ country }}/{{ monitor_copy1.previous_page_number }}">&laquo;上一页</a>
        </li>
    {% else %}
        <li>
        &laquo;上一页
        </li>
    {% endif %}
    {% for index in monitor_copy1.paginator.page_range %}

        {% if index == monitor_copy1.number %}
            <li class="active">
            {{ index }}/{{ monitor_copy1.paginator.num_pages }}
            </li>
{#        {% else %}#}
{#            <li>#}
{#                <a href="/showtable/{{ index }}">{{ index }}</a>#}
{#            </li>#}
        {% endif %}
    {% endfor %}
    {% if monitor_copy1.has_next %}
        <li>
            <a href="/showtable/{{ country }}/{{ monitor_copy1.next_page_number}}">下一页&raquo;</a>
        </li>
        {% else %}
        <li>
        下一页&raquo;
        </li>
    {% endif %}
{#    <li class="gotopage">#}
{#        <span>跳转到第</span>#}
{#            <input width="30px" height="30px"/>#}
{#        <span>页</span>#}
{#        <a id="tiaozhuang" href="#">跳转</a>#}
{#    </li>#}
    <li class="gotoresult" style="margin-left: 200px">
        <a target="_blank" href="{% url 'oneApp:show_result' country 'ug' %}">查看本科监控结果</a>
    </li>
    <li class="gotoresult">
        <a target="_blank" href="/showResult/{{ country }}/pg/">查看研究生监控结果</a>
    </li>
</ul>
<ul class="statecode">
    <li><span>注释</span></li>
    <li>404: 页面链接失效</li>
    <li>403: 页面禁止访问</li>
    <li>200: 页面结构变化</li>
    <li>200: 页面内容变化</li>
</ul>
</body>
</html>